export const ADMIN_HTML=`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive">
<title>SkinPlan — Access Control</title>
<style>
:root{--bg:#111332;--panel:#272764;--line:#454597;--text:#fff;--muted:#bcc2ea;--green:#2fc7a0;--red:#ff6b86;--amber:#f2a84a}
*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#10122f,#151741 60%,#10122f);color:var(--text);min-height:100vh}.shell{max-width:1120px;margin:auto;padding:24px}.hero,.card{background:var(--panel);border:1px solid var(--line);border-radius:20px;padding:20px;box-shadow:0 16px 45px #05061d55}.hero{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:16px}.hero h1{margin:0;font-size:26px}.muted{color:var(--muted);font-size:12px;line-height:1.5}.actions{display:flex;gap:8px;flex-wrap:wrap}button,a.btn{border:0;border-radius:11px;padding:10px 13px;font:inherit;font-weight:800;cursor:pointer;text-decoration:none;background:#45479a;color:white}.primary{background:linear-gradient(90deg,#6556ff,#df4fc0)!important}.danger{background:#702e48!important}.good{background:#1c6b5c!important}input{width:100%;border:1px solid #58599a;background:#1a1c4b;color:#fff;border-radius:11px;padding:11px;font:inherit}.grid{display:grid;grid-template-columns:1.1fr 1.1fr 1.3fr 1fr auto;gap:9px;align-items:end}.field label{display:block;font-size:11px;color:#d4d9ff;margin-bottom:5px}.status{margin-top:12px;padding:10px 12px;border-radius:11px;background:#1b1e50;border:1px solid #4a4c91;color:#dbe0ff;font-size:12px}.status.err{border-color:var(--red);color:#ffd6de}.status.ok{border-color:var(--green);color:#c9fff0}.tableWrap{overflow:auto;margin-top:14px}table{width:100%;border-collapse:collapse;min-width:900px}th,td{text-align:left;border-bottom:1px solid #454789;padding:11px 9px;font-size:12px;vertical-align:top}th{color:#cfd4fb;font-size:10px;text-transform:uppercase;letter-spacing:.04em}.badge{display:inline-block;padding:5px 8px;border-radius:999px;font-size:10px;font-weight:900;background:#4b4c91}.badge.active{background:#166f5c}.badge.off{background:#7a3048}.badge.expired{background:#7b571e}.rowActions{display:flex;gap:6px;flex-wrap:wrap}.rowActions button{padding:7px 9px;font-size:11px}.sectionTitle{display:flex;justify-content:space-between;gap:12px;align-items:center}.sectionTitle h2{margin:0}.card{margin-bottom:16px}@media(max-width:850px){.grid{grid-template-columns:1fr 1fr}.grid .wide{grid-column:1/-1}.hero{align-items:flex-start;flex-direction:column}}
</style>
</head>
<body><main class="shell">
<section class="hero"><div><h1>SkinPlan Access Control</h1><div class="muted">Create customer logins, revoke access instantly, reset passwords and set optional licence expiry dates.</div></div><div class="actions"><a class="btn primary" href="/api/app">Open SkinPlan</a><a class="btn" href="/api/admin?view=formulary">Formulary view</a><button id="logoutBtn" class="danger" type="button">Log out</button></div></section>
<section class="card"><div class="sectionTitle"><div><h2>Add customer</h2><div class="muted">Usernames are case-insensitive. Passwords must be at least 10 characters.</div></div></div><div class="grid" style="margin-top:14px"><div class="field"><label>Username</label><input id="newUsername" maxlength="40" autocomplete="off" placeholder="clinic-name"></div><div class="field"><label>Temporary password</label><input id="newPassword" type="password" maxlength="128" autocomplete="new-password" placeholder="10+ characters"></div><div class="field wide"><label>Customer / note (optional)</label><input id="newNote" maxlength="160" placeholder="Clinic or buyer name"></div><div class="field"><label>Valid through (optional)</label><input id="newExpiry" type="date"></div><button id="createBtn" class="primary" type="button">Create account</button></div><div id="status" class="status">Loading accounts…</div></section>
<section class="card"><div class="sectionTitle"><div><h2>Accounts</h2><div class="muted">Disabling an account or changing its password invalidates its current session immediately.</div></div><button id="refreshBtn" type="button">Refresh</button></div><div class="tableWrap"><table><thead><tr><th>Username</th><th>Status</th><th>Customer / note</th><th>Valid through</th><th>Last login</th><th>Actions</th></tr></thead><tbody id="usersBody"></tbody></table></div></section>
</main><script src="/api/admin?asset=client" defer></script></body></html>`;
