import Engine from './_private/engine.mjs';
import Selection from './_private/selection.mjs';
import {PRODUCTS,BRANDS,BRAND_TIERS,RANKINGS} from './_private/formulary.mjs';
import {requireSession,sameOrigin} from './_private/auth.mjs';

const METRICS=[
  ['acne','Acne'],['blackhead','Blackhead'],['pore','Pore'],['oil','Oil'],['bacteria','Bacteria'],
  ['surfaceSensitivity','Surface sensitivity'],['deepSensitivity','Deep sensitivity'],['surfaceSpot','Surface spot'],
  ['deepSpot','Deep spot'],['spotHeat','Spot heat'],['skinColor','Skin colour'],['wrinkle','Wrinkle'],
  ['collagen','Collagen'],['texture','Texture']
];
const PRODUCT_BY_ID=new Map(PRODUCTS.map(p=>[p.id,p]));

const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)));
const text=(v,max=500)=>String(v??'').trim().slice(0,max);
function deriveLevel(v){v=Number(v);if(v<=29)return 5;if(v<=49)return 4;if(v<=69)return 3;if(v<=89)return 2;return 1}
function esc(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function escAttr(v){return esc(v).replace(/`/g,'&#96;')}
function roman(n){return ['','I','II','III','IV','V'][Number(n)]||String(n)}

function normalize(body){
  const raw=body?.state||{};
  const baumann=text(raw.baumann,4);
  if(!/^[OD][SR][PN][WT]$/.test(baumann))throw new Error('Invalid Baumann profile.');
  const metrics={};
  for(const [id,label] of METRICS){
    const src=raw.metrics?.[id];if(!src)throw new Error(`Missing ${label} score.`);
    const score=clamp(src.score,0,100);if(!Number.isFinite(score))throw new Error(`Invalid ${label} score.`);
    metrics[id]={
      score,level:deriveLevel(score),source:text(src.source,80),
      originalScore:Number.isFinite(Number(src.originalScore))?clamp(src.originalScore,0,100):score,
      originalSource:text(src.originalSource||src.source,80)
    };
  }
  const audit=Array.isArray(raw.audit)?raw.audit.slice(-100).map(a=>({label:text(a?.label,80),from:clamp(a?.from,0,100),to:clamp(a?.to,0,100),at:text(a?.at,60)})):[];
  const state={loaded:true,demo:!!raw.demo,baumann,moisture:raw.moisture==null?null:clamp(raw.moisture,0,100),skinAge:raw.skinAge==null?null:clamp(raw.skinAge,0,150),totalScore:raw.totalScore==null?null:clamp(raw.totalScore,0,1000),metrics,audit};
  const sf=body?.safety?.flags||{};
  const flags=Object.fromEntries(['pregnant','trying','breastfeeding','eczema','rosacea','rx','procedure','allergy','currentActive','redFlagLesion','redFlagAcne','redFlagInfection'].map(k=>[k,!!sf[k]]));
  const sd=body?.safety?.details||{};
  const details={rx:text(sd.rx),procedure:text(sd.procedure),allergy:text(sd.allergy),currentActive:text(sd.currentActive),redFlag:text(sd.redFlag)};
  const changed=METRICS.some(([id])=>Number(metrics[id].score)!==Number(metrics[id].originalScore));
  const correctionReason=text(body?.safety?.correctionReason,500);
  if(changed&&!correctionReason)throw new Error('A reason is required for manual X3 score correction.');
  const enabledRaw=body?.selection?.enabledMap||{};
  const enabledMap=Object.fromEntries(BRANDS.map(b=>[b,enabledRaw[b]!==false]));
  const strategy=body?.selection?.strategy==='budget'?'budget':'clinical';
  const priorityBrand=BRANDS.includes(body?.selection?.priorityBrand)?body.selection.priorityBrand:'';
  return {state,flags,details,correctionReason,changed,selection:{enabledMap,strategy,priorityBrand}};
}

function safetyHoldReasons(f){const r=[];if(f.eczema)r.push('Active eczema / dermatitis');if(f.rosacea)r.push('Rosacea / persistent inflammatory redness');if(f.rx)r.push('Prescription skin treatment currently in use');if(f.procedure)r.push('Recent peel / laser / microneedling');if(f.currentActive)r.push('Current retinoid / benzoyl peroxide / exfoliating acid use');return r}
function safetyCautionReasons(f){const r=[];if(f.pregnant)r.push('Pregnancy — retinoid pathway excluded');if(f.trying)r.push('Trying to conceive — retinoid pathway excluded');if(f.breastfeeding)r.push('Breastfeeding — use conservative non-retinoid pathway and review product suitability');if(f.allergy)r.push('Known skincare allergy — exact allergen may be unknown; automatic product selection is paused');return r}
function redFlagReasons(f){const r=[];if(f.redFlagLesion)r.push('New / changing / bleeding / ulcerated pigmented lesion');if(f.redFlagAcne)r.push('Painful nodular/cystic or scarring acne');if(f.redFlagInfection)r.push('Possible infection, severe swelling, blistering or rapidly worsening rash');return r}

function rawRanked(role){return (RANKINGS[role]||[]).map(id=>PRODUCT_BY_ID.get(id)).filter(Boolean)}
function picker(selection){
  return function pick(role){
    const result=Selection.choose(rawRanked(role),{enabledMap:selection.enabledMap,strategy:selection.strategy,priorityBrand:selection.priorityBrand,brandTiers:BRAND_TIERS});
    if(!result?.product)return null;
    return {...result.product,_selectionNote:result.note||'',_selectionType:result.type||'clinical'};
  }
}
function activeProtocol(p,cautious=false){
  const t=p?.therapy||'active';
  if(t==='pigment_am')return {timing:'am',nights:0,maintenanceNights:0,minGap:0,frequency:'Use once each morning initially; sunscreen remains mandatory.',instructions:['Apply before moisturiser/sunscreen.','If other products from the same active family are added, follow the manufacturer label maximum for combined applications.']};
  if(t==='retinoid')return {timing:'pm',nights:1,maintenanceNights:2,minGap:2,frequency:'Start 1 evening/week for 1–2 weeks, then 2 non-consecutive evenings/week only if comfortable.',instructions:['Use a small amount on dry skin, followed by moisturiser.','During introduction, keep retinoid and direct-acid/BHA treatments on separate evenings. If the skin is stable later, any combined routine should be clinician-reviewed rather than assumed to be permanently incompatible.']};
  if(t==='bha'||t==='bha_pigment'||t==='multi_acid'||t==='blemish_acid')return {timing:'pm',nights:cautious?1:2,maintenanceNights:2,minGap:2,frequency:cautious?'Start once weekly; increase to twice weekly only if comfortable.':'Start 2 non-consecutive evenings/week.',instructions:['Use as the only exfoliating treatment active that evening during introduction.','Keep direct-acid/BHA and retinoid treatments on separate evenings at first. Later combination should depend on tolerance and clinician review, not on a blanket incompatibility rule.']};
  if(t==='azelaic')return {timing:'pm',nights:cautious?2:3,maintenanceNights:3,minGap:1,frequency:cautious?'Start 1–2 non-consecutive evenings/week; increase slowly to 3 if comfortable.':'Start 3 non-consecutive evenings/week; keep recovery nights.',instructions:['Use after cleansing, then moisturise.','During introduction, keep azelaic acid on separate treatment evenings from retinoid/direct-acid routines. If the skin remains stable, later simplification or combination can be clinician-reviewed.']};
  if(t==='blemish')return {timing:'pm',nights:cautious?3:4,maintenanceNights:4,minGap:0,frequency:cautious?'Start on 3 evenings/week; increase gradually if comfortable.':'Use on 4 evenings/week initially.',instructions:['Use as the single targeted blemish treatment in that routine.','If dryness or irritation appears, reduce frequency and add recovery nights.']};
  if(t==='pigment')return {timing:'pm',nights:cautious?2:3,maintenanceNights:3,minGap:1,frequency:cautious?'Start 2 non-consecutive evenings/week; increase gradually.':'Start 3 evenings/week, keeping recovery nights.',instructions:['Use as the single dedicated pigmentation treatment in that evening routine.','Do not add another exfoliating/retinoid treatment on the same evening.']};
  if(t==='peptide')return {timing:'pm',nights:3,maintenanceNights:3,minGap:0,frequency:'Use 3 evenings/week on non-acid recovery-style nights.',instructions:['Keep this on different evenings from direct acids/BHA in this conservative programme.','Retinoid can be considered only in a later stable phase if still needed.']};
  if(t==='ageing_support')return {timing:'pm',nights:3,maintenanceNights:3,minGap:0,frequency:'Use 3 evenings/week as the non-retinoid ageing-support routine.',instructions:['Use on treatment/recovery evenings as shown in the weekly table.','If irritation develops, reduce frequency rather than adding more actives.']};
  return {timing:'pm',nights:2,maintenanceNights:3,minGap:1,frequency:'Start on 2 non-consecutive evenings/week and increase only if comfortable.',instructions:['Use one treatment active at a time.']};
}

function buildPlan(ctx){
  const {state,flags:f,details,selection}=ctx;const pick=picker(selection);
  const requirePick=(role,label)=>{const p=pick(role);if(p)return p;throw new Error(`No product remains available for ${label||role}. Enable at least one compatible brand.`)};
  const rawLevels={};for(const [id] of METRICS)rawLevels[id]=state.metrics[id].level;
  const levels=Engine.concernLevels(rawLevels),B=state.baumann;
  const holdReasons=safetyHoldReasons(f),cautionReasons=safetyCautionReasons(f),redFlags=redFlagReasons(f);
  const hardHold=redFlags.length>0,softHold=holdReasons.length>0,allergyProductPause=f.allergy,withholdProducts=hardHold||allergyProductPause;
  const basePolicy=Engine.basePolicy({baumann:B,moisture:state.moisture,levels});
  const base=withholdProducts?null:{cleanser:requirePick(basePolicy.cleanserRole,'cleanser'),moisturiser:requirePick(basePolicy.moisturiserRole,'moisturiser'),spf:requirePick(basePolicy.spfRole,'sunscreen'),barrierSerum:pick('barrier_support'),rescue:pick('rescue_balm')};
  const barrierFirst=Engine.barrierFirst(levels,B),concerns=Engine.orderedConcerns(levels,B);
  const plan={levels,base,hardHold,softHold,allergyProductPause,withholdProducts,holdReasons,cautionReasons,redFlags,safetyDetails:details,barrierFirst,phases:[],avoid:[],referral:[],goal:'',mode:'',selected:[]};
  if(base?.barrierSerum)plan.selected.push(base.barrierSerum);if(base)plan.selected.push(base.cleanser,base.moisturiser,base.spf);
  const oneActivePhase=(concern,cautious=false)=>{
    const reproductiveCaution=f.pregnant||f.trying||f.breastfeeding;
    const treatmentSensitive=reproductiveCaution||B[1]==='S'||levels.barrier>=3;
    const ageingSensitive=treatmentSensitive||levels.ageing===3;
    const d=Engine.phaseDecision(concern,levels,{sensitive:concern==='ageing'?ageingSensitive:treatmentSensitive});
    if(!d.kind)return {title:'',active:null,protocol:null,frequency:'',instructions:[],covers:[]};
    const labels={acne_pigment_shared_robust:'a shared blemish + pigmentation treatment for robust skin',acne_pigment_shared_sensitive:'a lower-irritation shared blemish + pigmentation treatment',acne_treatment:'blemish treatment',pigment_only:'pigmentation treatment',congestion_treatment:'congestion treatment',ageing_sensitive:'non-retinoid ageing support',ageing_retinoid:'retinoid'};
    const role=d.kind==='ageing_retinoid'?'ageing_retinoid_starter':d.kind;
    const active=requirePick(role,labels[d.kind]);const protocol=activeProtocol(active,cautious||(concern==='ageing'&&ageingSensitive));
    const instructions=[...protocol.instructions];if(!instructions.some(x=>/manufacturer|label frequency/i.test(x)))instructions.push('This is a conservative starter schedule. If well tolerated after 2–4 weeks, increase only toward the current manufacturer label frequency and never above it.');
    const covers=Engine.expandedCovers(active,d.covers,levels);const ph={title:d.title,active,protocol,frequency:protocol.frequency,instructions,covers,triggeredBy:d.covers.slice()};
    if(concern==='acne'&&d.kind==='acne_treatment')ph.instructions.push('If acne is painful, nodular/cystic or scarring, cosmetic skincare is not enough.');
    return ph;
  };
  const addRemaining=(start,coveredInitial,cautiousFirst)=>{const covered=new Set(coveredInitial||[]);let n=start,first=true;for(const concern of concerns){if(covered.has(concern.key))continue;const ph=oneActivePhase(concern.key,first?cautiousFirst:true);if(!ph.active)continue;for(const c of ph.covers||[])covered.add(c);ph.title=(first?`Phase ${n} · Next 6–8 weeks after the previous phase is stable — `:`Phase ${n} · After a 6–8 week reassessment — `)+ph.title;ph.frequency=(first?'Begin only after the previous phase is stable. ':'Advance only if the concern is still relevant at reassessment and the previous phase is tolerated. ')+ph.frequency;plan.phases.push(ph);plan.selected.push(ph.active);n++;first=false;}};
  if(hardHold){plan.mode='Clinical red flag — automated treatment withheld';plan.goal='Show the X3 findings without starting an automated cosmetic treatment pathway while the clinical red flag is unresolved.';plan.phases.push({title:'Current status — clinical review first',active:null,protocol:null,frequency:'Do not use the automated formulary to start new treatment products from this report.',instructions:['Address the recorded red flag first. The X3 findings can still be reviewed and documented.'],covers:[]});}
  else if(allergyProductPause){plan.mode='Allergy review — product selection paused';plan.goal='Keep the report usable while avoiding automatic named-product selection when a skincare allergy is recorded.';plan.phases.push({title:'Current status — ingredient / allergy check first',active:null,protocol:null,frequency:'Continue only products already known to be tolerated. Do not start an automatically selected named product from this report until the allergy has been checked.',instructions:['The allergy detail field is optional; leaving it blank does not block this report.'],covers:[]});}
  else if(softHold){plan.mode='Safety review — recovery routine';plan.goal='Generate a useful basic plan without adding a new treatment active while the selected safety item is being reviewed.';plan.phases.push({title:'Current phase — simple recovery routine',active:null,protocol:null,frequency:'Use the simple cleanser / moisturiser / sunscreen foundation and avoid automatically adding a new treatment active for now.',instructions:['The exact product / procedure detail can be added if known, but is not required to generate this report.','Review the positive safety item before starting a new acid, retinoid or other treatment active.'],covers:[]});}
  else if(barrierFirst){plan.mode='Barrier recovery first';plan.goal='Stabilise device-detected sensitivity/barrier concern before introducing one targeted active.';plan.phases.push({title:'Phase 1 · Minimum 2 weeks — Barrier recovery',active:null,protocol:null,frequency:'Barrier-focused routine every day. Continue beyond 2 weeks if sensitivity is not stable.',instructions:['No salicylic acid or retinoid during this starter phase.','Do not progress until the skin has been comfortable for at least 7 days with no persistent burning, marked redness, swelling or peeling.'],covers:['barrier']});addRemaining(2,['barrier'],true);}
  else {const primary=concerns[0];if(primary){const ph=oneActivePhase(primary.key,B[1]==='S'||levels.barrier===3);ph.title='Phase 1 · First 6–8 weeks — '+ph.title;ph.frequency='Start with this single treatment pathway. '+ph.frequency;plan.phases.push(ph);if(ph.active)plan.selected.push(ph.active);plan.mode=ph.title.replace(/^Phase 1 · First 6–8 weeks — /,'');plan.goal='Treat the highest-priority X3 concern with one treatment pathway at a time.';addRemaining(2,ph.covers||[],true);}else{plan.mode='Maintenance';plan.goal='Maintain barrier function and UV protection without unnecessary actives.';plan.phases.push({title:'Maintenance',active:null,protocol:null,frequency:'Simple routine only.',instructions:['No treatment active is required from the current X3 profile.'],covers:[]});}}
  plan.avoid.push('Introduce only one new treatment pathway at a time.','During introduction, keep azelaic acid, direct acids/BHA and retinoids on separate treatment evenings. Later combination is a tolerance/clinician-review decision rather than a blanket incompatibility.','Keep peptide treatment on different evenings from direct acids/BHA in this conservative programme.','Later phases are conditional: re-check tolerance and whether the earlier concern still needs treatment before advancing.','Stop a new active if persistent burning, swelling, blistering, rash or marked worsening occurs.');
  if(f.pregnant||f.trying)plan.avoid.push('Retinoids are excluded while pregnant or trying to conceive.');if(f.breastfeeding)plan.avoid.push('Breastfeeding is recorded as a caution; this version keeps the ageing pathway non-retinoid and the intended products should still be checked for suitability before supply.');if(f.currentActive)plan.avoid.push('A retinoid, benzoyl peroxide or exfoliating acid is already in use; the report stays available, but no new treatment active is auto-started until the current routine is reviewed.');if(f.allergy)plan.avoid.push('A skincare allergy is recorded. Do not supply an automatically selected named product until ingredients have been checked against the known or suspected allergen.');
  if(state.metrics.acne.level>=4)plan.referral.push('The X3 acne score is a device screening signal, not a diagnosis. If clinical acne is present and is persistent, widespread, nodular/cystic or scarring, this cosmetic plan is not a substitute for pharmacist/GP/dermatology assessment.');if(state.metrics.surfaceSpot.level>=5||state.metrics.spotHeat.level>=5)plan.referral.push('New, changing, asymmetric or bleeding pigmentation/lesions need medical assessment rather than cosmetic treatment.');if(f.redFlagLesion)plan.referral.unshift('Clinical red flag recorded: new / changing / bleeding / ulcerated pigmented lesion. Do not target this lesion cosmetically; arrange appropriate medical assessment.');if(f.redFlagAcne)plan.referral.unshift('Clinical red flag recorded: painful nodular/cystic or scarring acne. Cosmetic skincare alone is not an adequate management plan; arrange appropriate clinical assessment.');if(f.redFlagInfection)plan.referral.unshift('Clinical red flag recorded: possible infection, severe swelling, blistering or rapidly worsening rash. Stop automated treatment selection and arrange prompt clinical assessment.');
  return plan;
}

function productImg(p){const fallback=`/api/product-image?id=${encodeURIComponent(p.id)}`;const src=String(p.image||'').startsWith('assets/')?`/${p.image}`:String(p.image||'');return `<img src="${escAttr(src)}" alt="${escAttr(p.name)}" loading="lazy" data-fallback="${escAttr(fallback)}">`}
function useText(p){const generic={cleanser:'Use a small amount and cleanse gently with lukewarm water.',moisturiser:'Apply a comfortable layer over face and neck.',spf:'Apply generously as the final morning step. During sustained outdoor exposure, reapply about every 2 hours and after swimming, sweating or towel-drying.',barrier:'Apply a thin layer / 2–3 drops as directed.',active:'Use only on the scheduled treatment nights.',ageing:'Use on the scheduled ageing-support nights.',retinoid:'Use only on scheduled retinoid nights.',support:'Use only when the plan specifically calls for it.',rescue:'Use only on local irritated/dry areas.'};return generic[p.role]||'Use as directed.'}
function routineStepTitle(p,index){if(index===0&&p.role==='cleanser')return 'Cleanse';if(p.role==='spf')return 'Protect SPF50+';if(p.role==='barrier')return 'Barrier support';if(p.role==='moisturiser')return 'Moisturise';if(p.role==='retinoid')return 'Retinoid treatment';if(p.role==='ageing')return 'Ageing support';if(p.role==='active'){if(/azelaic/i.test(p.name))return 'Azelaic-acid treatment';if(/salicylic|beta hydroxy|bha/i.test(p.name))return 'BHA / salicylic treatment';return 'Treatment active';}if(p.role==='pigment')return 'Pigmentation treatment';if(p.role==='support')return 'Support treatment';return 'Treatment step'}
function stepCard(p,title,i){return `<div class="step"><div class="n">${i+1}</div>${productImg(p)}<h4>${esc(title)}</h4><p><span class="brandname">${esc(p.brand)}</span><br>${esc(p.name)}</p>${p._selectionNote?`<div class="fallbackNote">${esc(p._selectionNote)}</div>`:''}<p>${esc(useText(p))}</p></div>`}
function routineCards(products){return `<div class="steps">${products.map((p,i)=>stepCard(p,routineStepTitle(p,i),i)).join('')}</div>`}
function selectedProductCardHTML(p){return `<div class="selectedCard">${productImg(p)}<div><b>${esc(p.brand)}</b><br>${esc(p.name)}${p._selectionNote?`<div class="fallbackNote">${esc(p._selectionNote)}</div>`:''}</div></div>`}
function isMorningDailyActive(p){return !!p&&(p.useTime==='am'||p.therapy==='pigment_am')}
function compactPhaseName(title){return title.replace(/^Phase \d+\s*·\s*/,'').replace(/\s*—\s*.*/,'').trim()}
function spacingRuleFor(p){if(!p)return 'No treatment-active spacing required.';const t=p.therapy||'active';if(t==='retinoid')return 'During introduction keep ≥2 nights between the first retinoid applications and separate retinoid from direct-acid/BHA treatment evenings; later combination requires tolerance-based clinician review.';if(['bha','bha_pigment','multi_acid','blemish_acid'].includes(t))return 'Keep ≥2 nights between the first exfoliating applications; never combine with a retinoid or another direct-acid treatment that evening.';if(t==='azelaic')return 'During introduction, keep ≥1 recovery/non-treatment night between applications.';if(t==='pigment_am')return 'Morning treatment; no PM spacing required. Follow label limits if combining products from the same active family.';if(t==='peptide')return 'Keep on different evenings from direct acids/BHA in this conservative programme.';return 'Use on separate treatment nights; add recovery nights if irritation develops.'}
function phaseWeekInfo(plan,state,phaseIndex){const phase=plan.phases[phaseIndex];const introduced=plan.phases.slice(0,phaseIndex+1).map((ph,idx)=>({phase:ph,index:idx,active:ph.active})).filter(x=>x.active);const amActives=introduced.filter(x=>x.phase.protocol?.timing==='am'),pmItems=introduced.filter(x=>x.phase.protocol?.timing!=='am');const sensitive=plan.barrierFirst||state.baumann[1]==='S';const prepared=pmItems.map(x=>({...x,key:x.active.id,count:x.index===phaseIndex?(x.phase.protocol?.nights||0):(x.phase.protocol?.maintenanceNights||x.phase.protocol?.nights||0),minGap:x.phase.protocol?.minGap||0}));const scheduled=Engine.scheduleWeek(prepared,{sensitive,currentIndex:phaseIndex});const counts=scheduled.counts.map(x=>({item:x,count:x.count}));const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],byKey=Object.fromEntries(prepared.map(x=>[x.key,x]));const week=(scheduled.week||days.map((_,i)=>({day:i,type:'recovery',key:null}))).map((d,i)=>{if(d.type!=='active')return {day:days[i],label:'Recovery',type:'recovery'};const item=byKey[d.key];return {day:days[i],label:routineStepTitle(item.active,1).replace(' treatment',''),type:'active'}});const amFreq=amActives.map(x=>`${x.active.brand} ${x.active.name}: daily AM`),pmFreq=counts.filter(x=>x.count>0).map(x=>`${x.item.active.brand} ${x.item.active.name}: ${x.count} night${x.count===1?'':'s'}/week`),paused=counts.filter(x=>x.count===0).map(x=>`${x.item.active.brand} ${x.item.active.name}`);const activeFreq=[...amFreq,...pmFreq].join('; ')||'Recovery routine only',pauseText=paused.length?` Earlier treatment paused in this example phase to avoid overcrowding: ${paused.join('; ')}. Reassess before deciding whether it still needs maintenance.`:'';const allActives=[...amActives,...pmItems.filter(x=>counts.find(c=>c.item.active.id===x.active.id)?.count>0)];const spacing=[...new Set(allActives.map(x=>spacingRuleFor(x.active)))].join(' ')+(allActives.filter(x=>x.phase.protocol?.timing!=='am').length>1?' Different evening treatment actives stay on separate evenings.':'');const morning=[plan.base.cleanser];if(plan.barrierFirst&&plan.base.barrierSerum)morning.push(plan.base.barrierSerum);amActives.forEach(x=>morning.push(x.active));morning.push(plan.base.moisturiser,plan.base.spf);return {phase,morning,week,activeFreq:activeFreq+pauseText,spacing:spacing||'No treatment-active spacing required.',counts}}
function phaseTriggerText(plan,ph){if(!ph.triggeredBy?.length)return '';const labels={acne:'Acne',pigment:'Pigmentation',congestion:'Congestion',ageing:'Ageing',barrier:'Barrier'};return ph.triggeredBy.map(k=>`${labels[k]||k} L${roman(plan.levels[k])}`).join(' + ')}
function shortProduct(p){return `${esc(p.brand)} — ${esc(p.name.replace(/\s+\d+\s*(ml|g).*$/i,''))}`}
function weeklyProgrammeTable(plan,state){const rows=plan.phases.map((ph,idx)=>{const x=phaseWeekInfo(plan,state,idx),trigger=phaseTriggerText(plan,ph);return `<tr><td class="summaryPhase">${esc(ph.title)}${trigger?`<div class="small" style="margin-top:6px"><b>Triggered by:</b> ${esc(trigger)}</div>`:''}</td><td>${x.morning.map(shortProduct).join('<br>')}</td><td><b>${esc(x.activeFreq)}</b><div class="weekMini">${x.week.map(d=>`<span class="${d.type}"><b>${esc(d.day)}</b><br>${esc(d.label)}</span>`).join('')}</div></td><td>${esc(x.spacing)}</td></tr>`}).join('');return `<div class="summaryWrap"><h3>Weekly programme at a glance</h3><div class="summaryHint">Use this table as the quick reference. Full morning/evening routines with product images are repeated underneath for every phase.</div><table class="summaryTable"><thead><tr><th>Phase / weeks</th><th>Morning products — every day</th><th>Weekly treatment frequency + example evenings</th><th>Spacing between treatment actives</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function phaseDetailedHTML(plan,state,phaseIndex){const phase=plan.phases[phaseIndex],introduced=plan.phases.slice(0,phaseIndex+1).map((ph,idx)=>({phase:ph,index:idx,active:ph.active})).filter(x=>x.active),weekInfo=phaseWeekInfo(plan,state,phaseIndex),countMap=new Map((weekInfo.counts||[]).map(x=>[x.item.active.id,x.count])),morningActives=introduced.filter(x=>isMorningDailyActive(x.active)),eveningActives=introduced.filter(x=>!isMorningDailyActive(x.active)&&(countMap.get(x.active.id)||0)>0),morning=[plan.base.cleanser];if(plan.barrierFirst&&plan.base.barrierSerum)morning.push(plan.base.barrierSerum);morningActives.forEach(x=>morning.push(x.active));morning.push(plan.base.moisturiser,plan.base.spf);const recovery=[plan.base.cleanser];if(plan.barrierFirst&&plan.base.barrierSerum)recovery.push(plan.base.barrierSerum);recovery.push(plan.base.moisturiser);const trigger=phaseTriggerText(plan,phase);let html=`<div class="phaseDetailed"><h3>${esc(phase.title)}</h3>${trigger?`<div class="phaseIntro"><b>Triggered by:</b> ${esc(trigger)}</div>`:''}<div class="phaseIntro"><b>Phase instruction:</b> ${esc(phase.frequency)}</div>${phase.instructions.length?`<ul class="phaseIntro">${phase.instructions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<div class="phaseRule"><b>Example weekly spacing:</b> ${weekInfo.week.map(d=>`${esc(d.day)}: ${esc(d.label)}`).join(' · ')}</div><div class="phaseRoutineBand morning">☀ MORNING — EVERY DAY DURING THIS PHASE</div>${routineCards(morning)}`;if(eveningActives.length===0)html+=`<div class="phaseRoutineBand recovery">☾ EVENING — EVERY NIGHT DURING THIS PHASE</div><div class="phaseRoutineNote">Barrier/recovery routine only.</div>${routineCards(recovery)}`;else{for(const item of eveningActives){const current=item.index===phaseIndex,freq=current?item.phase.frequency:`Continue this treatment only at the tolerated frequency established in ${compactPhaseName(item.phase.title)}.`;html+=`<div class="phaseRoutineBand treatment">☾ EVENING — ${esc(routineStepTitle(item.active,1).toUpperCase())} NIGHTS</div><div class="phaseRoutineNote">${esc(freq)}</div>${routineCards([plan.base.cleanser,item.active,plan.base.moisturiser])}`;}html+=`<div class="phaseRoutineBand recovery">☾ EVENING — RECOVERY NIGHTS</div><div class="phaseRoutineNote">Use this routine on evenings not assigned to one of the treatment routines above.</div>${routineCards(recovery)}<div class="phaseRule"><b>Important:</b> treatment-night routines are separate. Do not use two listed treatment actives on the same evening unless the plan explicitly says to do so.</div>`;}return html+'</div>'}
function safetyBannerHTML(plan){const reasons=[...(plan.holdReasons||[]),...(plan.cautionReasons||[]),...(plan.redFlags||[])];if(!reasons.length)return '';const d=plan.safetyDetails||{},details=[];if(d.rx)details.push(`<li><b>Prescription:</b> ${esc(d.rx)}</li>`);if(d.procedure)details.push(`<li><b>Procedure:</b> ${esc(d.procedure)}</li>`);if(d.allergy)details.push(`<li><b>Allergy:</b> ${esc(d.allergy)}</li>`);if(d.currentActive)details.push(`<li><b>Current active:</b> ${esc(d.currentActive)}</li>`);if(d.redFlag)details.push(`<li><b>Red-flag note/action:</b> ${esc(d.redFlag)}</li>`);const title=plan.hardHold?'CLINICAL RED FLAG — AUTOMATED TREATMENT WITHHELD':plan.allergyProductPause?'ALLERGY RECORDED — NAMED-PRODUCT SELECTION PAUSED':plan.softHold?'SAFETY CAUTION — REPORT GENERATED IN RECOVERY MODE':'SAFETY NOTE — PLAN ADAPTED AUTOMATICALLY';return `<div class="criticalHold"><h3>${title}</h3><b>Recorded item(s):</b><ul>${reasons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${details.length?`<b>Optional detail recorded:</b><ul>${details.join('')}</ul>`:'<div style="margin-top:6px"><b>No extra detail entered.</b> This does not block report generation.</div>'}</div>`}
function devicePriorityHTML(state){const groups={urgent:[],continuous:[],preventive:[]};for(const [id,label] of METRICS){const m=state.metrics[id],txt=`${label} ${m.score} · L${roman(m.level)}`;if(m.level>=4)groups.urgent.push(txt);else if(m.level===3)groups.continuous.push(txt);else groups.preventive.push(txt)}return `<div class="rpriority"><div><h4>X3 high priority</h4>${groups.urgent.map(esc).join('<br>')||'None'}</div><div><h4>Continuous</h4>${groups.continuous.map(esc).join('<br>')||'None'}</div><div><h4>Preventive</h4>${groups.preventive.map(esc).join('<br>')||'None'}</div></div>`}
function auditTrailHTML(ctx){if(!ctx.changed)return '';const rows=(ctx.state.audit||[]).map(a=>`<tr><td>${esc(a.label)}</td><td>${esc(a.from)}</td><td>${esc(a.to)}</td><td>${esc(a.at)}</td></tr>`).join('');return `<div class="auditBox"><b>Manual X3 correction record</b><div>Report generated: ${esc(new Date().toISOString())}</div><div style="margin-top:5px"><b>Reason:</b> ${esc(ctx.correctionReason)}</div><table><thead><tr><th>Indicator</th><th>From</th><th>To</th><th>Change time</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Manual correction present; no change event captured.</td></tr>'}</tbody></table></div>`}
function withheldPlanHTML(plan){const allergyOnly=plan.allergyProductPause&&!plan.hardHold;return `<div class="phase"><h3>${allergyOnly?'Named-product selection paused':'Automated treatment plan withheld'}</h3><p style="font-size:11px;line-height:1.6">${allergyOnly?'The X3 findings and safety record are still generated. Because an allergy is recorded and this engine does not perform ingredient-level allergen matching, it does not automatically name products to start. Continue only products already known to be tolerated and verify ingredients before supply.':'The X3 findings are shown for review, but no automatic treatment-active schedule is produced while the clinical red flag remains unresolved. The report itself remains available for documentation and review.'}</p></div>`}
function renderReport(ctx,plan){const selectedUnique=[...new Map(plan.selected.filter(Boolean).map(p=>[p.id,p])).values()];const planBody=plan.withholdProducts?withheldPlanHTML(plan):`${weeklyProgrammeTable(plan,ctx.state)}<div class="band phaseband">FULL ROUTINE FOR EACH PHASE</div>${plan.phases.map((_,idx)=>phaseDetailedHTML(plan,ctx.state,idx)).join('')}`;return `<div class="rhead"><div><h1>Personalised Skin Maintenance Plan</h1><div>Generated from ${ctx.state.demo?'SkinPlan demo data':'X3 device data'} · SkinPlan v17.21.5</div></div><div><b>Plan</b><br><small>${esc(plan.mode)}</small></div></div><div class="rmeta"><div>Baumann<b>${esc(ctx.state.baumann)}</b></div><div>Moisture<b>${ctx.state.moisture??'—'}${ctx.state.moisture!=null?'%':''}</b></div><div>Skin age<b>${ctx.state.skinAge??'—'}</b></div><div>Total score<b>${ctx.state.totalScore??'—'}</b></div></div>${safetyBannerHTML(plan)}${devicePriorityHTML(ctx.state)}<div class="goodbox"><b>Plan goal:</b> ${esc(plan.goal)}</div>${planBody}<div class="warnbox"><b>Do not use / pause</b><ul>${plan.avoid.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>${plan.referral.length?`<div class="warnbox"><b>When this plan is not enough / referral</b><ul>${plan.referral.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${!plan.withholdProducts?`<div class="phase"><h3>Products selected by the ranking engine</h3><div class="selectedGrid">${selectedUnique.map(selectedProductCardHTML).join('')}</div></div>`:''}${auditTrailHTML(ctx)}<div class="footer">Cosmetic skincare maintenance guidance only — not a diagnosis or prescription. X3 scores/Levels and Baumann type are device-derived decision inputs. Safety and red-flag answers adapt the plan automatically; optional detail fields may be left blank. Brand settings can change which compatible ranked product is selected, but do not override safety holds. Check current product labels and availability before supply.</div>`}

export async function POST(request){
  const auth=await requireSession(request);if(auth)return auth;
  if(!sameOrigin(request))return Response.json({error:'Origin rejected.'},{status:403,headers:{'Cache-Control':'no-store'}});
  try{const body=await request.json();const ctx=normalize(body);const plan=buildPlan(ctx);const html=renderReport(ctx,plan);return Response.json({html,mode:plan.mode},{headers:{'Cache-Control':'no-store, no-cache, must-revalidate','Pragma':'no-cache','X-Content-Type-Options':'nosniff'}})}catch(error){return Response.json({error:error?.message||'Unable to generate report.'},{status:400,headers:{'Cache-Control':'no-store'}})}
}
export function GET(){return new Response(null,{status:405,headers:{'Allow':'POST','Cache-Control':'no-store'}})}
